close #7, #8: Initial model introduction, deserialization
bypolinafox/10-elephants pull request #14
Opened 2021-12-09 19:05 UTC by daria25D

Add structs for Meals, MealModel, Ingredient.
Add deserialization of Meals and MealModel, use GenericCodingKeys for decoding.

2021-12-09 20:22 UTC, kirilldenisov approved these changes

2021-12-09 21:56 UTC, aldonin requested changes
Посмотри, пожалуйста, у тебя файлы не лежат в проекте, висят просто в воздухе

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +struct  Meals: Decodable {
```suggestion
struct Meals: Decodable {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/GenericCodingKeys.swift
> +public class GenericCodingKeys: CodingKey {
Тут и ниже не нужна публичность
```suggestion
class GenericCodingKeys: CodingKey {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +             idMeal,
Предложу явно писать все кейсы, так обычно меньше диффа в плане расставке запятых
```suggestion
         case idMeal
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +        let decodedKeysCommon = RequiredCodingKeys.allCases.map({ $0.rawValue })
Тут и ниже можно короче
```suggestion
        let decodedKeysCommon = RequiredCodingKeys.allCases.map(\.rawValue)
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +        let filteredKeysNames = filteredKeys.map({ $0.stringValue })
```suggestion
        let filteredKeysNames = filteredKeys.map(\.stringValue)
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +    enum RequiredCodingKeys: String, CodingKey, CaseIterable {
```suggestion
    private enum RequiredCodingKeys: String, CodingKey, CaseIterable {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +    enum OptionalCodingKeys: String, CodingKey, CaseIterable {
```suggestion
    private enum OptionalCodingKeys: String, CodingKey, CaseIterable {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +        if let nonSplitTags = try customContainer.decode(String?.self, forKey: .strTags) {
Кажется вместо if-else можно написсать так
```suggestion
        self.tags = try customContainer.decodeIfPresent(String.self, forKey: .strTags).flatMap{ $0.components(separatedBy: ",") }
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +        let filteredKeys = otherContainer.allKeys.filter({
Можно не писать
```suggestion
        let filteredKeys = otherContainer.allKeys.filter {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +            if let ingredientKey = GenericCodingKeys(stringValue: ingredientKeyName) {
Можно убрать одну вложенность
```suggestion
            if let ingredientKey = GenericCodingKeys(stringValue: ingredientKeyName),
               let measureKey = GenericCodingKeys(stringValue: measureKeyName) {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +struct MealModel: Decodable {
Предложу убрать Model, это dto описатель?
```suggestion
struct Meal: Decodable {
```

2021-12-09 21:56 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +struct MealModel: Decodable {
Давай может уберем конформансе в экстеншен и код по coding/decoding туда же, чтобы основная структура была почище?
Туда же наверное можно и *CodingKeys перенессти

2021-12-10 08:54 UTC, aldonin approved these changes
Давайте лить, миноры можно отдельно потом исправить

2021-12-10 08:54 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/GenericCodingKeys.swift
> +class GenericCodingKeys: CodingKey {
```suggestion
final class GenericCodingKeys: CodingKey {
```

2021-12-10 08:54 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/Meals.swift
> +struct Meal{
```suggestion
struct Meal {
```

2021-12-10 08:56 UTC, merged