close #2: Network layer
bypolinafox/10-elephants pull request #23
Opened 2021-12-10 14:13 UTC by bypolinafox

Added network layer with four base methods (wiki)

2021-12-10 17:00 UTC, daria25D commented on Ten Elephants/Ten Elephants/Models/MealDetailsModel.swift
> +struct MealDetailsModel {
Is this struct used anywhere?

2021-12-11 07:31 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Models/MealDetailsModel.swift
> +struct MealDetailsModel {
Поправила

2021-12-11 11:49 UTC, aldonin requested changes

2021-12-11 12:13 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Network/NetworkServiceProtocol.swift
> +    func getMealDetails(id: Int, completion: (() -> ())?)
А почему у нас тут именно NetworkError, а не обычный Error?

2021-12-11 12:20 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Network/Requests/BaseRequest.swift
> +                // place for deserialization
Это у Даши в коде вроде

2021-12-11 12:24 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Network/NetworkServiceProtocol.swift
> +    func getMealDetails(id: Int, completion: (() -> ())?)
И как быть с другими типами возвр результата?

2021-12-11 17:47 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/NetworkServiceProtocol.swift
> +    func getMealDetails(id: Int, completion: (() -> ())?)
Потому что обычный Error не дает контекста наружу
Кажется, что сетевого слоя должны возвращаться сетевые ошибки, а не любые возможные

2021-12-13 07:18 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Network/NetworkServiceProtocol.swift
> +    func getMealDetails(id: Int, completion: (() -> ())?)
А что если у нас произошла ошибка десериализации, например?
И я еще не нашла такой класс ошибок, здесь нужно что-то кастомное писать?

2021-12-13 12:17 UTC, aldonin approved these changes

2021-12-13 12:17 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/MealPageController.swift
> +            let ingridientCell = factory.makeIngridientCell(name: ingridient.name, measure: ingridient.measure ?? "", emoji: "😋")
@alexxingplus видимо тут надо будет поправить

2021-12-13 12:17 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/TabBarController.swift
> +        let MealC = MealPageController(mealData: Meal(id: "", name: "", thumbnailLink: nil, category: nil, area: nil, instructions: nil, youTubeLink: nil, tags: nil, ingredients: nil))
Надо не забыть эту печаль выпилить

2021-12-13 12:22 UTC, merged