close #26: image fetching and caching
bypolinafox/10-elephants pull request #38
Opened 2021-12-13 12:55 UTC by kirilldenisov

add CachedImageFetcher class, implement fetching for WideCellView in TrendPageController

2021-12-13 22:30 UTC, aldonin requested changes

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +    init(countLimit: Int) {
Можно убрать конструктор без параметров и написать
```suggestion
    init(countLimit: Int = Constants.cacheCountLimit) {
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +class CachedImageFetcher {
```suggestion
final class CachedImageFetcher {
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +    let cachedImages = NSCache<NSURL, UIImage>()
```suggestion
    private let cachedImages = NSCache<NSURL, UIImage>()
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +    var loadingResponses = [NSURL: [(UIImage?) -> Swift.Void]]()
```suggestion
    private var loadingResponses = [NSURL: [(UIImage?) -> Swift.Void]]()
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +    func image(url: NSURL) -> UIImage? {
```suggestion
    private func image(url: NSURL) -> UIImage? {
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +                return
Зачем тут return?

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/TrendPageController.swift
> +              let ulr = NSURL(string: link) else {
```suggestion
              let url = NSURL(string: link) else {
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/TrendPageController.swift
> +        guard let link = item.thumbnailLink,
```suggestion
        guard let url = item.thumbnailLink.flatMap(NSURL.init(string:)) else { return cell }
```

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Views/WideCellView.swift
> +        static let shadowColor = UIColor.label.cgColor
Зачем это тут?

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +                  let blocks = self.loadingResponses[url], error == nil else {
давай только weak self, чтобы без циклов

2021-12-13 22:30 UTC, aldonin commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +            self.cachedImages.setObject(image, forKey: url, cost: responseData.count)
Мы не выставляешь ограничение по cost, есть смысл указывать эту стоимость при добавлении?
```suggestion
            self.cachedImages.setObject(image, forKey: url)
```

2021-12-14 08:58 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +    init(countLimit: Int) {
а почему так лучше?

2021-12-14 09:06 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Cache/CachedImageFetcher.swift
> +    let cachedImages = NSCache<NSURL, UIImage>()
а зачем?

2021-12-14 09:11 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Controllers/TrendPageController.swift
> +        guard let link = item.thumbnailLink,
что-то так на мой вкус совсем не круто и неинтуитивно выглядит

2021-12-14 09:12 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Views/WideCellView.swift
> +        static let shadowColor = UIColor.label.cgColor
заметили, что черная тень в темном режиме совсем пропадает, такой простой ляп не хотелось оставлять

2021-12-14 11:54 UTC, aldonin approved these changes

2021-12-14 11:55 UTC, merged