close: #42
bypolinafox/10-elephants pull request #50
Opened 2021-12-14 12:32 UTC by kirilldenisov

Implemented storing array of liked objects in UserDefaults

2021-12-14 22:01 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Controllers/MealPageController.swift
> +        mealData.isLiked = !mealData.isLiked
я не придумал, как сделать лучше, надо как-то предусмотреть в классе кнопки, что в нее можно подать ссылку на параметр в mealData. Мы вроде не планируем пока менять стейт на какой-либо другой странице

2021-12-15 06:07 UTC, alexxingplus commented on Ten Elephants/Ten Elephants/Controllers/MealPageController.swift
> +        mealData.isLiked = !mealData.isLiked
Можно ещё не mealData.isLiked к кнопке приравнивать, а наоборот: задавать стейт кнопки исходя из стейта mealData, то есть
sender.isLiked = mealData.isLiked

В любом случае нужно их связать, чтобы не было ситуации, когда по ошибке у них противоположные значения меняются одновременно

2021-12-15 11:38 UTC, bypolinafox requested changes

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Controllers/MealPageController.swift
> +        self.likeButton.isLiked = mealData.isLiked
Для того, чтобы проставить какие-то значения, можно, наверное, вытащить это во viewDidLoad. В ините круто оставить только присвоение mealData

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Controllers/TabBarController.swift
> +        )
Может это гитхаб шалит, но тут, кажется, поехали отступы

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +class DBDataProviderUD: DBDataProvider {
final

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +    }
А мы хотим потом сюда добавлять какие-то еще поля, кроме лайкнуто/не лайкнуто? если да, то я бы сделала это поле конкретно для лайка, а для даты (если она нужна будет когда-то целиком) сделала бы отдельный метод.

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +}
Еще думала, может как-то переназвать класс, я не сразу догадалась без контекста задачи, что это UserDefaults сторэдж (там просто только в конце стоит UD). Может как-нибудь типа UserDefaultsDataProvider? (Это название тоже далеко от идеала, просто предложение)

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +    }
И кстати тогда можно будет новое поле isLiked сделать приватным только на сет, и брать значение о том, лайкнуто или нет, беря свойство. @aldonin у этого есть смысл?

2021-12-15 11:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Views/LikeButton.swift
> +        self.isLiked = false
А почему поставили на false? Нам разве не нужно выставлять в зависимости от состояния в модельке?

2021-12-15 11:42 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +            let obj = UserDefaults.standard.object(forKey: Constants.userDefaultsKey)
я не люблю много последовательных операций в одну строчку, я такое плохо читаю

2021-12-15 11:43 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Controllers/TabBarController.swift
> +        )
это автоформаттер удалил трейлинг пробелы, которые икскод проставил при переходе на другую строку

2021-12-15 11:50 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Controllers/TabBarController.swift
> +        )
а, ну все, да, что  такое бывает

2021-12-15 12:28 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +    }
не понял, как ты хочешь сделать

2021-12-15 12:28 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +}
норм

2021-12-15 12:29 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/UIModels/DBDataProvider.swift
> +    }
ща, поговорю с Кириллом и скажу

2021-12-15 12:29 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Views/LikeButton.swift
> +        self.isLiked = false
мы проставляем в контроллере, сама кнопка с моделью напрямую не связана

2021-12-15 12:38 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/UIModels/UIMeals.swift
> +struct UIMeal {
Стоит удалить неиспользуемые поля

2021-12-15 13:17 UTC, bypolinafox approved these changes

2021-12-15 13:18 UTC, merged