Add loading of data from network
bypolinafox/10-elephants pull request #51
Opened 2021-12-14 12:40 UTC by daria25D

Instead of stub data load data from network.
While data is not loaded, show loading indicator for vertical section and label animation for horizontal section. Close #37 , close #40  .

2021-12-14 16:59 UTC, aldonin requested changes

2021-12-14 16:59 UTC, aldonin commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProviderNetwork.swift
> +    lazy var networkService = NetworkService()
```suggestion
    private lazy var networkService = NetworkService()
```

2021-12-14 16:59 UTC, aldonin commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProviderNetwork.swift
> +                completionHandler(.failure(.unparsableData))
так наверное неправильно делать
надо ошибки сетевого слоя  транссформировать в ошибки сслоя провайдера, а не всегда одну и ту же отдавать

2021-12-15 07:49 UTC, alexxingplus approved these changes

2021-12-15 10:09 UTC, alexxingplus approved these changes

2021-12-15 11:13 UTC, kirilldenisov approved these changes

2021-12-15 11:16 UTC, kirilldenisov approved these changes

2021-12-15 11:41 UTC, bypolinafox commented
Там 2 коммита, может объединим?

2021-12-15 11:41 UTC, bypolinafox commented
И еще конфликты появились

2021-12-15 11:49 UTC, bypolinafox requested changes

2021-12-15 11:49 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProviderNetwork.swift
> +    private lazy var networkService = NetworkService()
у нас есть протокол NetworkServiceProtocol, может попробовать через него тут нетворк сервис позвать?

2021-12-15 11:49 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProvider.swift
> +    case serverError(error: Error)
Там в одном из еще не смердженных моих прок есть NetworkFetchingErrors, нужно нам будет потом их как-нибудь подружить, чтобы структурно одинаковые енамы не плодить

2021-12-15 11:49 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProviderNetwork.swift
> +}
кажется, эти два метода делают одно и то же? Может, я что-то не заметила. А зачем нам вообще эта обертка сверху над NetworkService? Мы же можем сразу его юзать из логического кода

2021-12-15 11:51 UTC, daria25D commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProvider.swift
> +    case serverError(error: Error)
я думаю, можно отдельным коммитом сделать рефакторинг error-handling, там еще пара мест есть проблемных

2021-12-15 11:56 UTC, daria25D commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProviderNetwork.swift
> +}
У нас сейчас есть задача переписать этот протокол, чтобы он больше соответствовал network service 
Про то, зачем он, - я бы сказала, что обертка сверху скрывает детали имплементации (откуда конкретно мы берем данные - может мы захотим для тестов брать что-то дефолтное, например), но наверное тут @aldonin лучше может объяснить

2021-12-15 12:08 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/DataProvider/MealsDataProviderNetwork.swift
> +}
приняла

2021-12-15 13:18 UTC, aldonin submitted a review, later dismissed

2021-12-15 13:28 UTC, aldonin approved these changes

2021-12-15 13:29 UTC, bypolinafox approved these changes

2021-12-15 13:29 UTC, merged