close #46: exponential backoff
bypolinafox/10-elephants pull request #52
Opened 2021-12-14 13:11 UTC by bypolinafox

2021-12-14 21:50 UTC, alexxingplus commented on Ten Elephants/Ten Elephants/AppDelegate.swift
> +    let networkService = NetworkService()
А зачем нам в делегате NetworkService?.. Вроде бы в твоём коммите он больше нигде не юзается

2021-12-14 22:08 UTC, aldonin requested changes

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/Requests/RequestUtils.swift
> +final class DelayCounter {
в отдельный файлик

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/Requests/RequestUtils.swift
> +    private let minDelay: Double = 0.1
Все эти параметры через аргументы конструктора

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/Requests/RequestUtils.swift
> +final class DelayCounter {
Название не оч
```suggestion
final class ExponentialBackoffDelayCalculator {
```

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/NetworkService.swift
> +
лишний дифф

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/NetworkService.swift
> +                let model = try JSONDecoder().decode(T.self, from: data)
лишний дифф, не вижу смысла

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/NetworkService.swift
> +
то же сссамое

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/AppDelegate.swift
> +
не нужный дифф

2021-12-14 22:08 UTC, aldonin commented on Ten Elephants/Ten Elephants/Network/NetworkService.swift
> +        request(type: .detailsById(id: id)) { [weak self] (result: Result<Meals, NetworkFetchingError>) in
Нужен еще один заход подумать как ссделать без копипасты кода, выглядит не очень

2021-12-15 11:39 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Network/NetworkService.swift
> +        request(type: .detailsById(id: id)) { [weak self] (result: Result<Meals, NetworkFetchingError>) in
вот я чет думала, но ничего не придумала :(((

2021-12-15 13:28 UTC, aldonin approved these changes

2021-12-15 13:31 UTC, merged