close #32: search page 🔎
bypolinafox/10-elephants pull request #62
Opened 2021-12-14 21:06 UTC by alexxingplus

I've added working search page, now app can search meals by name and ingredient. Also I've added some funcs and requests to NetworkService: now it's easy to fetch latest meals or fetch meals by multi-ingredient

2021-12-14 22:00 UTC, aldonin requested changes

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/MealSuggestionDataSource.swift
> +    private weak var imageFetcher: CachedImageFetcher?
А почему weak?

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/MealSuggestionDataSource.swift
> +        guard let link = meal.thumbnailLink, let url = NSURL(string: link) else {return suggestionCell}
```suggestion
        guard let url = meal.thumbnailLink.flatMap(NSURL(string:)) else { return suggestionCell }
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Views/SearchPageViewFactory.swift
> +//        title.text = Constants.recentMealsTitle
удалить?

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Views/IngredientSuggestionCell.swift
> +        titleLabel.text = "Прикол"
??

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/MealSuggestionDataSource.swift
> +final class MealSuggestionDataSource: NSObject, UICollectionViewDataSource {
Разве нужен NSObject?
```suggestion
final class MealSuggestionDataSource: UICollectionViewDataSource {
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/ResultMealDataSource.swift
> +final class ResultMealDataSource: NSObject, UICollectionViewDataSource {
```suggestion
final class ResultMealDataSource: UICollectionViewDataSource {
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/ResultMealDataSource.swift
> +    private weak var imageFetcher: CachedImageFetcher?
```suggestion
    private let imageFetcher: CachedImageFetcher
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/SearchPageController.swift
> +        networkService.searchMealByName(name: searchText) { [weak self] (result) in
Наверное правильно не через networkService, а через dataProvider, которрый этот сервис исспольузет?
@daria25D ?

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/SearchPageController.swift
> +                case .failure(_):
```suggestion
                case .failure:
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/SearchPageController.swift
> +//        guard let searchText = searchBar.text, !searchText.isEmpty else {
??

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/RecentsProvider/RecentsProvider.swift
> +                fatalError(error.localizedDescription)
КОгда нет интернета будем полуать fatalError 
Так плохо делать

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/RecentsProvider/RecentsProviderProtocol.swift
> +    typealias mealsCompletion = (Result<Meals, NetworkFetchingError>) -> Void
Типы с большой буквы
```suggestion
    typealias MealsCompletion = (Result<Meals, NetworkFetchingError>) -> Void
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Views/IngredientSuggestionCell.swift
> +    lazy var ingredientName = makeTitleLabel()
Оно в конктструкторе ссоздается, от lazy толку 0

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Views/IngredientSuggestionCell.swift
> +        super.init(frame: .zero)
Тогда уж
```suggestion
        super.init(frame: frame)
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Views/IngredientSuggestionCell.swift
> +        ingredientName.frame = self.bounds
```suggestion
        ingredientName.frame = bounds
```

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/RecentsProvider/RecentsProvider.swift
> +    func addMealToRecents(meal: Meal) {
давай вообще не будем его пока добавлять

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/RecentsProvider/RecentsProvider.swift
> +        guard recentMeals.meals.isEmpty else {
Вот тту не понял: не надо после того как получили recent их положить в recentMeals?

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/ingredientSuggestions.swift
> +    let emoji: String?
нужен optional?

2021-12-14 22:00 UTC, aldonin commented on Ten Elephants/Ten Elephants/Models/ingredientSuggestions.swift
> +    var fullName: String {
лучше в extension

2021-12-14 22:20 UTC, kirilldenisov commented on Ten Elephants/Ten Elephants/Views/SearchPageViewFactory.swift
> +//        title.text = Constants.recentMealsTitle
еще бы вынести размер шрифта в константы

2021-12-15 06:24 UTC, alexxingplus commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/MealSuggestionDataSource.swift
> +    private weak var imageFetcher: CachedImageFetcher?
Я так делал, чтобы не было retain cycle.
На экране поиска у нас есть 2 collectionView, которые показывают по сути одно и то же. Поэтому я создал imageFetcher в контроллере и передаю в датасорсы. Датасорсы являются property контроллера, и сами юзают другие property контроллера - поэтому я так и написал. 

Но после твоего коммента ещё раз подумал, что вроде бы тут retain cycle нет - датасорс ссылается на property, а не на контроллер. Поправлю, спасибо!

2021-12-15 06:26 UTC, alexxingplus commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/MealSuggestionDataSource.swift
> +final class MealSuggestionDataSource: NSObject, UICollectionViewDataSource {
Я пробовал убрать NSObject - Xcode на это ругался. Попробую ещё раз

2021-12-15 06:32 UTC, alexxingplus commented on Ten Elephants/Ten Elephants/Models/ingredientSuggestions.swift
> +    let emoji: String?
Optional не обязателен, но я бы его оставил. Лучше явно видеть, что эмодзи может не быть, а так можно забыть проверить на emoji.isEmpty и что-то может отображаться неправильно. Но прямо сейчас в словаре с предложенными ингредиентами у всех ингредиентов есть эмодзи, и если менять ничего не будем - то можно optional убрать, в принципе

2021-12-15 07:05 UTC, alexxingplus commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/MealSuggestionDataSource.swift
> +final class MealSuggestionDataSource: NSObject, UICollectionViewDataSource {
![image](https://user-images.githubusercontent.com/43221673/146139517-0d7d75f0-f98c-49b9-8a0a-dd5eac8e83a5.png)

2021-12-15 11:56 UTC, bypolinafox commented on Ten Elephants/Ten Elephants/Controllers/TabBarController.swift
> +    private var networkService = NetworkService()
лучше тут вытащить нетворк сервис через протокол

2021-12-15 13:04 UTC, daria25D commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/SearchPageController.swift
> +        networkService.searchMealByName(name: searchText) { [weak self] (result) in
Да, после пр #51 нужно будет использовать networkService как параметр инициализации для dataProvider'а

2021-12-15 13:05 UTC, daria25D commented on Ten Elephants/Ten Elephants/Controllers/SearchPage/SearchPageController.swift
> +        networkService.searchMealByName(name: searchText) { [weak self] (result) in
Но к протоколу еще не добавлена функция поиска по id

2021-12-15 13:19 UTC, aldonin submitted a review, later dismissed

2021-12-15 13:42 UTC, kirilldenisov approved these changes

2021-12-15 13:42 UTC, merged