close #63, #74: random meal page
bypolinafox/10-elephants pull request #81
Opened 2021-12-16 08:18 UTC by alexxingplus

I have changed the layout of MealPageController, also there's a random tab now and emoji 🤘

2021-12-16 12:45 UTC, kirilldenisov approved these changes

2021-12-16 12:45 UTC, kirilldenisov commented on TenElephants/TenElephants/Views/MealViewFactory.swift
> +        static let defaultEmojis: [String] = ["😋", "🤤", "🥣", "🥢", "🤩", "🍴", "🤪"]
```suggestion
        static let defaultEmojis: [String] = ["😋", "🤤", "🥣", "🥢", "🍴", "🍽", "🥡"]
```

2021-12-16 12:45 UTC, kirilldenisov commented on TenElephants/TenElephants/Models/IngredientSuggestions.swift
> +let ingredientSuggestions: [String: IngredientSuggestion] = [
Хранить в Plist?

2021-12-16 17:38 UTC, kirilldenisov approved these changes

2021-12-16 19:49 UTC, aldonin requested changes

2021-12-16 19:49 UTC, aldonin commented on TenElephants/TenElephants/Controllers/TrendPageController.swift
> +        else { fatalError("No section provided") }
Никаких fatalError-ов
```suggestion
        else { assertionFailure("No section provided") }
```

2021-12-16 19:49 UTC, aldonin commented on TenElephants/TenElephants/Models/IngredientSuggestions.swift
> +let ingredientSuggestions: [String: IngredientSuggestion] = [
Так ок

2021-12-16 19:49 UTC, aldonin commented on TenElephants/TenElephants/Views/RoundButtonWithBlur.swift
> +enum RoundButtonType {
положить внутрь класса, эта штука без классса не имеет смысла

2021-12-17 09:38 UTC, aldonin approved these changes

2021-12-17 09:38 UTC, aldonin commented on TenElephants/TenElephants/Controllers/MealPageController.swift
> +        _ = imageFetcher.fetch(url: url, completion: { [weak self] image in
Заменим потом на `@discardableResult`

2021-12-17 09:38 UTC, aldonin commented on TenElephants/TenElephants/Views/RoundButtonWithBlur.swift
> +    enum buttonType {
Типы с заглавной буквы
```suggestion
    enum ButtonType {
```

2021-12-17 09:38 UTC, aldonin commented on TenElephants/TenElephants/Views/RoundButtonWithBlur.swift
> +        switch type {
Это лучше в extension
```swift
extension  RoundButtonWithBlur.ButtonType {
  var icon: UIImage {
    switch self { ... }
  }
}
```

2021-12-17 09:39 UTC, merged